### ISSUE TITLE
`btrfs-progs` not available on Debian 8

### ISSUE THREAD

**Issue by MaxiBoether** [lpirl/ansible-roles#7]
In `file-system-maintenance.yml` (managed_host), we are installing the btrfs-progs package if we find mountpoints. This fails if the package is not available, for example on Debian 8.

Should we add an error handler that checks whether the package is available?

**Comment by lpirl** [comment]
Debian 8/Jessie reached end of life June 2018, so I hesitate adding extra "complexity" for long-outdated releases (see also [this comment](https://github.com/lpirl/ansible-roles/pull/4#issuecomment-721036656)).

If you want to prepare a PR, I'd rather add a conditional to the package name which uses `btrfs-tools` for Debian <= 8 and `btrfs-progs` otherwise.

**Comment by MaxiBoether** [comment]
I've created a PR with your suggested conditional: https://github.com/lpirl/ansible-roles/pull/13

Thank you very much for considering the merge :)

**Comment by lpirl** [comment]
Thanks for #13 , merged into [branch `debian-8-compat`](/lpirl/ansible-roles/tree/debian-8-compat) to not clutter master too much with code for Debian Jessie.
